// <auto-generated />
using System;
using IqraPearls.DataDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IqraPearls.Migrations
{
    [DbContext(typeof(IqraDbContext))]
    [Migration("20231114185211_ReturnRequest")]
    partial class ReturnRequest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("IqraPearls.Dtos.CartDto", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.ToTable("CartDto");
                });

            modelBuilder.Entity("IqraPearls.Dtos.OrderDto", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<Guid>("OrderNumber")
                        .HasColumnType("char(36)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<bool>("isPaid")
                        .HasColumnType("tinyint(1)");

                    b.ToTable("OrderDto");
                });

            modelBuilder.Entity("IqraPearls.Model.Cart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrderId");

                    b.ToTable("Carts");
                });

            modelBuilder.Entity("IqraPearls.Model.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("ParentCommentId")
                        .HasColumnType("int");

                    b.Property<string>("ProductComment")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("IqraPearls.Model.Customers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AddressCity")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GeneratedSalt")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Customerss");
                });

            modelBuilder.Entity("IqraPearls.Model.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<Guid>("OrderNumber")
                        .HasColumnType("char(36)");

                    b.Property<bool>("isPaid")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("IqraPearls.Model.Preview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("NoOfReveiws")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("ReviewValue")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("PReviews");
                });

            modelBuilder.Entity("IqraPearls.Model.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Price")
                        .HasColumnType("double");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SellersId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SellersId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("IqraPearls.Model.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("IqraPearls.Model.ProductRequestRelationship", b =>
                {
                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("ReturnRequestModelId")
                        .HasColumnType("int");

                    b.HasKey("ProductId", "ReturnRequestModelId");

                    b.HasIndex("ReturnRequestModelId");

                    b.ToTable("ProductRequestRelationship");
                });

            modelBuilder.Entity("IqraPearls.Model.ReturnRequestModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<Guid>("OrderNumber")
                        .HasColumnType("char(36)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("ReasonForReturn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("ReturnChoice")
                        .HasColumnType("int");

                    b.Property<int>("ReturnStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeReturnRequested")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("ReturnRequestTable");
                });

            modelBuilder.Entity("IqraPearls.Model.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("ReviewValue")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("IqraPearls.Model.SellerReturnRequestModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<Guid>("OrderNumber")
                        .HasColumnType("char(36)");

                    b.Property<int>("ProductIdToReturn")
                        .HasColumnType("int");

                    b.Property<int>("ProductIdonOrder")
                        .HasColumnType("int");

                    b.Property<int>("QuantityToReturn")
                        .HasColumnType("int");

                    b.Property<string>("ReasonForAcceptanceOrDenial")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ReasonForReturn")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SellersId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeReturnRequested")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("isRequestAccepted")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("SellersId");

                    b.ToTable("SellerReturnRequestTable");
                });

            modelBuilder.Entity("IqraPearls.Model.Sellers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("AddressCity")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GeneratedSalt")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PostCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StoreDescription")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StoreName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("Sellerss");
                });

            modelBuilder.Entity("IqraPearls.Model.Wishlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Wishlists");
                });

            modelBuilder.Entity("System.Collections.Generic.List<int>", b =>
                {
                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.ToTable("List<int>");
                });

            modelBuilder.Entity("IqraPearls.Model.Cart", b =>
                {
                    b.HasOne("IqraPearls.Model.Customers", "Customer")
                        .WithMany("ListOfCartProduct")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IqraPearls.Model.Order", null)
                        .WithMany("ListofProductOrdered")
                        .HasForeignKey("OrderId");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("IqraPearls.Model.Comment", b =>
                {
                    b.HasOne("IqraPearls.Model.Product", "product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product");
                });

            modelBuilder.Entity("IqraPearls.Model.Order", b =>
                {
                    b.HasOne("IqraPearls.Model.Customers", "customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("customer");
                });

            modelBuilder.Entity("IqraPearls.Model.Preview", b =>
                {
                    b.HasOne("IqraPearls.Model.Product", "product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product");
                });

            modelBuilder.Entity("IqraPearls.Model.Product", b =>
                {
                    b.HasOne("IqraPearls.Model.Sellers", "sellers")
                        .WithMany("Tosell")
                        .HasForeignKey("SellersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("sellers");
                });

            modelBuilder.Entity("IqraPearls.Model.ProductImage", b =>
                {
                    b.HasOne("IqraPearls.Model.Product", "Product")
                        .WithMany("ImageUrlList")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("IqraPearls.Model.ProductRequestRelationship", b =>
                {
                    b.HasOne("IqraPearls.Model.Product", "Products")
                        .WithMany("PRRelations")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IqraPearls.Model.ReturnRequestModel", "_ReturnRequest")
                        .WithMany("PRRelations")
                        .HasForeignKey("ReturnRequestModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Products");

                    b.Navigation("_ReturnRequest");
                });

            modelBuilder.Entity("IqraPearls.Model.Review", b =>
                {
                    b.HasOne("IqraPearls.Model.Product", "product")
                        .WithOne("review")
                        .HasForeignKey("IqraPearls.Model.Review", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("product");
                });

            modelBuilder.Entity("IqraPearls.Model.SellerReturnRequestModel", b =>
                {
                    b.HasOne("IqraPearls.Model.Sellers", "Seller")
                        .WithMany("ReturnRequest")
                        .HasForeignKey("SellersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("IqraPearls.Model.Sellers", b =>
                {
                    b.HasOne("IqraPearls.Model.Order", null)
                        .WithMany("ListOfSellers")
                        .HasForeignKey("OrderId");
                });

            modelBuilder.Entity("IqraPearls.Model.Wishlist", b =>
                {
                    b.HasOne("IqraPearls.Model.Customers", "Customer")
                        .WithMany("ListOfWishlistProduct")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("IqraPearls.Model.Customers", b =>
                {
                    b.Navigation("ListOfCartProduct");

                    b.Navigation("ListOfWishlistProduct");
                });

            modelBuilder.Entity("IqraPearls.Model.Order", b =>
                {
                    b.Navigation("ListOfSellers");

                    b.Navigation("ListofProductOrdered");
                });

            modelBuilder.Entity("IqraPearls.Model.Product", b =>
                {
                    b.Navigation("ImageUrlList");

                    b.Navigation("PRRelations");

                    b.Navigation("review")
                        .IsRequired();
                });

            modelBuilder.Entity("IqraPearls.Model.ReturnRequestModel", b =>
                {
                    b.Navigation("PRRelations");
                });

            modelBuilder.Entity("IqraPearls.Model.Sellers", b =>
                {
                    b.Navigation("ReturnRequest");

                    b.Navigation("Tosell");
                });
#pragma warning restore 612, 618
        }
    }
}
